# Describes the format for available Netatmo services
set_camera_light:
  target:
    entity:
      integration: netatmo
      domain: light
  fields:
    camera_light_mode:
      required: true
      selector:
        select:
          options:
            - "on"
            - "off"
            - "auto"

set_schedule:
  target:
    entity:
      integration: netatmo
      domain: climate
  fields:
    schedule_name:
      example: Standard
      required: true
      selector:
        text:

set_scheduled_room_temperature:
  target:
    entity:
      integration: netatmo
      domain: climate
  fields:
    zone_name:
      required: true
      selector:
        select:
          options:
            - Eco
            - Comfort
            - Comfort+
            - Night
    temperature:
      example: 20
      required: true
      selector:
        number:
          min: 10
          max: 30

set_persons_home:
  target:
    entity:
      integration: netatmo
      domain: camera
  fields:
    persons:
      example: "[Alice, Bob]"
      required: true
      selector:
        object:

set_person_away:
  target:
    entity:
      integration: netatmo
      domain: camera
  fields:
    person:
      example: Bob
      selector:
        text:

register_webhook:
unregister_webhook:
